### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by gagan-bansal** [anomal/RainbowVis-JS#11]
Very nice lib, I am using it in many applications.
Now I require it with browserify ie. as commanjs module. Would you please consider it publishing on npm?

**Comment by anomal** [comment]
I am unclear on what I need to add to make it a CommonJS module, and how to publish it to npm as "rainbowvis.js" (as npm does not allow capital letters (?)) without breaking the existing URL https://raw.githubusercontent.com/anomal/RainbowVis-JS/master/rainbowvis.js.

Please advise.

**Comment by gagan-bansal** [comment]
Please go through this [blog](http://evanhahn.com/make-an-npm-baby/) that explains how to make a module and publish it on npm and read more on [npm documentation](https://docs.npmjs.com/)
The URL for [rainbowvis.js](https://raw.githubusercontent.com/anomal/RainbowVis-JS/master/rainbowvis.js) is not used in npm, as it is a separate echo system. Though you should mention the github repo [URL](https://github.com/anomal/RainbowVis-JS.git) in package.json. 

Anyway this url can not be consumed directly from github, as github does not allow hotlinking. You can use some [alternate](http://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github) or cdn server.  

If any issue please let me know. such a nice library should be exposed to more users.
Later you should also consider test cases for this lib.

**Comment by anomal** [comment]
Thanks for forking.

I had an ad-hoc script that hotlinked to github years ago. I did not know they disabled hotlinking now.
