### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by aspergillusOryzae** [anomal/RainbowVis-JS#13]
Would it be possible to create a bower package?
http://bower.io/docs/creating-packages/

**Comment by anomal** [comment]
I am not familiar with that ecosystem.  You can create a bower package for it and request a pull.

**Comment by ahaverty** [comment]
For anyone else passing, looking for a bower package, and aren't aware of bower'ing from github:
`bower install git://github.com/anomal/RainbowVis-JS.git`

**Comment by anomal** [comment]
#14 should fix this.
