### ISSUE TITLE
Give permission for an MIT licensed derived work or switch license to MIT?

### ISSUE THREAD

**Issue by bldrvnlw** [anomal/RainbowVis-JS#17]
Dear anomal, 

I wish to use rainbowvis-js in a work (a website and a toolkit to be released later) that will be released under BSD or MIT license. According to the Eclipse License page ["Does the EPL allow me to ... include all or part of it in another program licensed under (BSD) license or other Open Source license"](https://eclipse.org/legal/eplfaq.php#USEINANOTHER) this is not possible without your permission. Could you please contact me at my work address [b (dot) van (underscore) lew (at) lumc (dot) nl] to discuss this? Alternatively would you consider changing to a BSD or MIT or Apache license?

Some background info: The website and toolkit are use for displaying very large interactive scatter plots (in a bioscience context) in a browser and linking them to choropleths. 

Regards
Baldur

**Comment by anomal** [comment]
I sent you an email, but according to the [EPL FAQ](http://www.eclipse.org/legal/eplfaq.php#EXAMPLE):

> **I‘m a programmer not a lawyer, can you give me a clear cut example of when something is or is not a derivative work?**
> If you have made a copy of existing Eclipse code and made a few minor revisions to it, that is a derivative work. If you"ve written your own Eclipse plug-in with 100% your own code to implement functionality not currently in Eclipse, then it is not a derivative work. Scenarios between those two extremes will require you to seek the advice of your own legal counsel in deciding whether your program constitutes a derivative work.

> *For clarity, merely interfacing or interoperating with Eclipse plug-in APIs (without modification) does not make an Eclipse plug-in a derivative work.*

(Italics mine)
